title: Gean Ramos
description: > # this means to ignore newlines until "baseurl:"
  O lugar onde as hist贸rias ganham vida! Junte-se a n贸s para romances arrebatadores, reflex玫es profundas e muitos mais. 
permalink: ':title.html'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.gean.me" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/geanramos #if your site has a twitter account, enter it here

# Author Settings
author: Gean Ramos # add your name
author-img: https://avatars.githubusercontent.com/u/6352393?v=4 # add your photo
avatar: https://avatars.githubusercontent.com/u/6352393?v=4 # add your photo
about-author: O lugar onde as hist贸rias ganham vida! Junte-se a n贸s para romances arrebatadores, reflex玫es profundas e muitos mais.  # add description
social-twitter: geanramos # add your Twitter handle
social-facebook: geanramos # add your Facebook handle
social-bluesky: did:plc:k3g67rs7si5va35yyhp7utk2 # add your Github handle
social-linkedin: geanramos # add your Linkedin handle
social-email: geanramos@gmail.com # add your Email address

# Disqus
discus-identifier: geanramos # add your discus identifier

# Tracker
analytics: G-TZBPFV014K # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 20
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
